landingPage/urls.py
from django.urls import path
from . import views

app_name = 'landingPage'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.profile, name='profile'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.books, name='books'),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
    path('',views.story9, name='story9'),
    path('signup/', views.signupPage, name='signup'),
	path('login/', views.loginPage, name='login'),  
	path('logout/', views.logoutPage, name='logout'),
]

storyMirsa2/urls.py
from django.urls import path, include
from django.contrib import admin
from story8.views import fungsi_data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingPage.urls')),
    path('profile/',include('story7.urls')),
    path('books/',include('story8.urls')),
    path('story9/',include('story9.urls')),
    path('data/', fungsi_data),
]

landingPage/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.



story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

landingPage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'page.html')

story7/views.py
from django.shortcuts import render
# Create your views here.
def profile(request):
    return render(request, 'profile.html')

story8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json


# Create your views here.
def books(request):
    response = {}
    return render(request,'books.html',response)

def fungsi_data(request):
    url= "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    print(ret.content)

    data = json.loads(ret.content)
    # data={'coba' :'ini'}
    return JsonResponse(data, safe=False)


story9/views.py

from django.shortcuts import render, redirect 
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm

# Create your views here.
#from .models import *

def signupPage(request):
	if request.user.is_authenticated:
		return redirect('/story9/')
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')

				return redirect('/story9/')
			

		context = {'form':form}
		return render(request, 'signup.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('/story9/')
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('/story9/')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'login.html', context)

def logoutPage(request):
	logout(request)
	return redirect('/story9/login')

@login_required(login_url='/story9/login')
def story9(request):
    return render(request, 'story9.html')

landingPage/templates/page.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 7 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section>
    <div class="section-title"> HALOO <br>SEMUAAA </div>
    <img class="pic" style="margin-top: 5px; margin-bottom: 20px;" src="{% static 'img/hi.png' %}">
</section>
{% endblock %}

story7/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story7 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section class="normal">
  <div class="section-title"> TENTANG AKU </div>

  <div class="accordion-container" >
    <div id="activity" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Aktifitas
        <div style="border-radius: 30px;">
          <button class="up"> ∧ </button>
          <button class="down" style="font-weight: bold;"> v </button>
        </div>
      </a>
      <div class="content">
        <p>Mencoba memahami setiap matkul dan berjuang buat ngerjain banyak tugas :'</p>
      </div>
    </div>

    <div id="experience" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Pengalaman
        <div>
          <button class="up"> ∧ </button>
          <button class="down" style="font-weight: bold;"> v </button>
        </div>
      </a>
      <div class="content">
        <ul>
          <li>Staff Administrasi DPM Fasilkom UI</li>
          <li>Staff Divisi Acara SIWAK-NG 2020</li>
          <li>Mentor OKK UI 2020</li>
        </ul>
      </div>
    </div>
    
    <div id="achievement" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Prestasi
        <div>
          <button class="up"> ∧ </button>
          <button class="down" style="font-weight: bold;"> v </button>
        </div>
      </a>
      <div class="content">
        <p> Tidur kurang dari 5 jam perhari </p>
      </div>
    </div>
    
    <div id="contact" class="set">
      <a href="#" class="bar d-flex justify-content-between">
        Kontak
        <div>
          <button class="up"> ∧ </button>
          <button class="down" style="font-weight: bold;"> v </button>
        </div>
      </a>
      <div class="content">
        <p> ig: @mirsalsa </p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

{% block script %}  <script src="{% static 'js/accordion.js' %}"></script> {% endblock %}

story8/templates/books.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story8 {% endblock %}

{% block content %}
{% include 'navbar.html' %}

<section id=books>
    <div class="section-title"> TEMUKAN BUKUMU! </div>

    <input  class="form-control" id=keyword placeholder="Ketik nama buku, misal: Laut Bercerita">
    <table class="table table-hover">
        <tbody id="daftarBuku"> 
        </tbody>
    </table>
</section>
{% endblock %}

{% block script %}  
<script type="text/javascript">
    $("#keyword").keyup(function(){
        var ketikan = $("#keyword").val();
        console.log(ketikan);
        $.ajax({
            url: '/data?q=' + ketikan,
            success: function(data) {
                //console.log(data);
                var array_items = data.items;
                //console.log(array_items);
                $("#daftarBuku").empty();
                for(i=0; i< array_items.length; i++){
                    var title = array_items[i].volumeInfo.title;
                    var authors = array_items[i].volumeInfo.authors;
                    var image = array_items[i].volumeInfo.imageLinks.smallThumbnail;
                    var rating = array_items[i].volumeInfo.averageRating;
                    var previewLink = array_items[i].volumeInfo.previewLink;
                    if(authors==undefined){
                        var authors = "-"
                    }
                    if(rating==undefined){
                        var rating = "-"
                    }
                    $("#daftarBuku").append(
                        "<tr>" + 
                        "<td>" + "<img src="+image+">"+ "</td>" +
                        "<td>" + "<b>" + title + "</b>" + "<br>" + 
                        "Authors: " + authors + "<br>" +
                        "Rating: " + rating + "<br>" +  "<br>" +
                        "<a id= preview class= button href=" + previewLink + '>Preview Book</a>'+
                        "</td>" +"</tr>");
                }
            }
        });
    });
</script>
{% endblock %}

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Story 9
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id=normal>
    <div class="container" id="container-login">  
        <div class="section-title"> LOGIN </div>
        <p style="text-align: center;">Silahkan login untuk melanjutkan</p>
        <br>
        
        <form id="formlogin" method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="username" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-10">
                  <input type="text" id="username" name= "username">
                </div>
              </div>
              <div class="form-group row">
                <label for="password" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                  <input type="password" id="password" name="password">
                </div>
              </div>
            <br>
            <input class="btn btn-dark login_btn" type="submit" value="Login">
        </form>
        <br>

        {% for message in messages %}
        <p id="messages">{{message}}</p>
        {% endfor %}	

        <p style="text-align: center;">
            Tidak punya akun? Silahkan daftarkan akun terlebih dahulu
            <a href="{%url 'story9:signup'%}"><br>
                Daftar disini</a>
        </p>
    </div>
</section>
{% endblock content %}

story9/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Story 9
{% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id=normal>
    <div class="container" id="container-login">
        
    <div class="section-title"> SIGN UP </div>
        <p style="text-align: center;">Sign up jika kamu belum memiliki akun</p>
        <br>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="username" class="col-sm-2 col-form-label">Username</label>
                <div class="col-sm-10">
                    {{form.username}}
                </div>
              </div>
              <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    {{form.email}}
                </div>
              </div>
              <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Password</label>
                <div class="col-sm-10">
                    {{form.password1}}
                </div>
              </div>
              <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Konfirmasi password</label>
                <div class="col-sm-10">
                    {{form.password2}}
                </div>
              </div>
            <br>
            <input class="btn btn-dark login_btn" type="submit" value="Sign Up" style="margin-left: 0px;">
        </form>
        <br>
        {{form.errors}}
        <br>
        <p style="text-align: center;">
            Sudah punya akun?
            <a href="{%url 'story9:login'%}"><br>
                Login di sini</a>
        </p>
    </div>
</section>
{% endblock content %}

story9/templates/story9.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Story 9 {% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section id=normal>
    <div class="section-title"> HALOO <br>{{user.username}}! </div>
    <br>
    <div style="text-align: center;">
        <img src="{% static 'img/halo.png' %}"  class="pic" style="margin-top: 5px; margin-bottom: 5px;" >
        <br>
    </div>
    <p style="text-align: center;">Ingin logout?
        <a href="{% url 'story9:logout' %}"><br>
            Logout</a>
    </p>
   
    
</section>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        {% block style %}{% endblock %}

        <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300&family=Monoton&family=Mulish&family=Sacramento&family=Sriracha&family=Unica+One&display=swap" rel="stylesheet">
        
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        
    {% block content %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.iconify.design/1/1.0.4/iconify.min.js"></script>

    {% block script %}
    {% endblock %}

    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'landingPage:index' %}">Masih Semangat?</a>
    <div class="col-auto">
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown mx-3">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                FITUR
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'story7:profile' %}">Story 7 PPW</a>
                <a class="dropdown-item" href="{% url 'story8:books' %}">Story 8 PPW</a>
                <a class="dropdown-item" href="{% url 'story9:story9' %}">Story 9 PPW</a>
            </div>
        </li>
      </ul>
    </div>
    </div>
    </div>
</nav>